FROM tungstenfabric/contrail-kubernetes-kube-manager:R2011-2021-01-29

COPY kube_config_db.py /usr/lib/python2.7/site-packages/kube_manager/common/kube_config_db.py
COPY vnc_pod.py /usr/lib/python2.7/site-packages/kube_manager/vnc/vnc_pod.py
